POST http://localhost/upload
Content-Type: application/json

{
  "image": "<imagem em base64>",
  "customer_code": "12345",
  "measure_datetime": "2024-06-28T18:21:44.404+03:00",
  "measure_type": "GAS"
}
###

GET http://localhost/images/47051162-e9fa-42eb-87a4-8023c2ac35af
###

PATCH http://localhost/confirm
Content-Type: application/json

{
  "measure_uuid": "194ec90a-dd1f-41db-86fc-55875d0fa618",
  "confirmed_value": 221
}
###

GET http://localhost/12345/list

###

GET http://localhost/12345/list?measure_type=WATER